#server:
#  port: 8761
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
    registerWithEureka: false
    fetchRegistry: false